### ISSUE TITLE
Does Calculator module include 'Prepared By', 'Prepared From', 'Logo', 'Net Sheet Report' screens?

### ISSUE THREAD

**Issue by DevarshiK** [rhodgex1/T365CalculatorScreens#1]
In Zeplin `Create Net Sheet Report` screen is part of `Calculate` tag and `Prepared For`, `Prepared By`, `Logo` screens are part of `Create Report` tag but in invision link each is part of `Calculate`.

Do I need to work on `Prepared For`, `Prepared By`, `Logo`, `Net Sheet Report` screens as part of `Calculator` module? Please confirm.

**Comment by rhodgex1** [comment]
They should be part of the calculate tag as well. I have added the tag
